### ISSUE TITLE
Display character limit for text boxes

### ISSUE THREAD

**Issue by nguyenadam** [jchacko11/eliminate-answers#3]
See title

**Comment by jchacko11** [comment]
Branch 'character-count' in the works

**Comment by jchacko11** [comment]
We can do something like this to link to character counts:
`function getData(q){
    var output = ""
    try{
        output = q[4][0][4][0][2][0]
        return output;
    }catch(e){
    }
}
FB_PUBLIC_LOAD_DATA_[1][1].map(getData)
`

**Comment by jchacko11** [comment]
We might have a problem with multiple pages because as far as I can see, we have to do this with indexes (the first item in the data array is the first question on the page). If we can do this with specific id's that would be ideal.

**Comment by jchacko11** [comment]
So it turns out there are indexes. I was able to solve this by making a smaller script that is inserted in the DOM to add data attributes to the form questions with the min/max values. The content script uses these to find how many characters are left.
